{"name": "test_sample01[123-123--]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location", "trace": ".0 = <list_iterator object at 0x10662f9d0>\n\n>   kwargs = {arg: kwargs[arg] if arg in kwargs else request.getfixturevalue(arg) for arg in args}\n\n../../../Automation/lib/python3.11/site-packages/pytest_bdd/scenario.py:204: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../../../Automation/lib/python3.11/site-packages/_pytest/fixtures.py:541: in getfixturevalue\n    fixturedef = self._get_active_fixturedef(argname)\n../../../Automation/lib/python3.11/site-packages/_pytest/fixtures.py:570: in _get_active_fixturedef\n    self._compute_fixture_value(fixturedef)\n../../../Automation/lib/python3.11/site-packages/_pytest/fixtures.py:647: in _compute_fixture_value\n    fixturedef.execute(request=subrequest)\n../../../Automation/lib/python3.11/site-packages/_pytest/fixtures.py:1079: in execute\n    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)\n../../../Automation/lib/python3.11/site-packages/pluggy/_hooks.py:501: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n../../../Automation/lib/python3.11/site-packages/pluggy/_manager.py:119: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n../../../Automation/lib/python3.11/site-packages/_pytest/setuponly.py:36: in pytest_fixture_setup\n    return (yield)\n../../../Automation/lib/python3.11/site-packages/_pytest/fixtures.py:1132: in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n../../../Automation/lib/python3.11/site-packages/_pytest/fixtures.py:906: in call_fixture_func\n    fixture_result = next(generator)\nsteps/conftest.py:30: in init_driver\n    driver = webdriver.Chrome(service=service,options=options)\n../../../Automation/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n../../../Automation/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py:49: in __init__\n    self.service.path = DriverFinder.get_path(self.service, options)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nservice = <selenium.webdriver.chrome.service.Service object at 0x106667ad0>, options = <selenium.webdriver.chrome.options.Options object at 0x106667b90>\n\n    @staticmethod\n    def get_path(service: Service, options: BaseOptions) -> str:\n        path = service.path\n        try:\n            path = SeleniumManager().driver_location(options) if path is None else path\n        except Exception as err:\n            msg = f\"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager.\"\n            raise NoSuchDriverException(msg) from err\n    \n        if path is None or not Path(path).is_file():\n>           raise NoSuchDriverException(f\"Unable to locate or obtain driver for {options.capabilities['browserName']}\")\nE           selenium.common.exceptions.NoSuchDriverException: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n../../../Automation/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py:44: NoSuchDriverException"}, "description": "../features/sample.feature: Verify the login functionality", "parameters": [{"name": "_pytest_bdd_example", "value": "{'Username': '123', 'Password': '123'}"}, {"name": "Username", "value": "''"}, {"name": "Password", "value": "''"}], "start": 1711773919068, "stop": 1711773919070, "uuid": "d2adf54d-f1d9-4cb2-9939-27038c1a62dc", "historyId": "aa800b01451927b0f97456ee7ee977c5", "testCaseId": "8781a52a01f4bb11b862418b60a465e1", "fullName": "steps.test_sample#test_sample01", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('Username', 'Password')"}, {"name": "tag", "value": "sample01"}, {"name": "parentSuite", "value": "steps"}, {"name": "suite", "value": "test_sample"}, {"name": "host", "value": "Saravanas-MacBook-Air.local"}, {"name": "thread", "value": "2252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "steps.test_sample"}]}